name: CI for LOMAP_ES4C

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  unit-e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci
    - run: npm --prefix webapp test --coverage --watchAll
    - run: CI=false && npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    #needs: [e2e-tests]
    needs: [unit-e2e-tests]
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        API_URI: http://${{ secrets.DEPLOY_HOST }}:5000/api
      with:
          name: arquisoft/lomap_es4c/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_URI
          
  deploy:
      needs: [unit-e2e-tests]
      name: gh-pages deploy
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --prefix webapp install
      - run: PUBLIC_URL=https://Raul-Alv.github.io/lomap_es4c/ npm --prefix webapp run build
      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@create-branch-if-needed-arg
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
            source-directory: 'webapp/build'
            destination-github-username: 'Raul-Alv'
            destination-repository-name: 'lomap_es4c'
            user-email: UO265210@uniovi.es
            commit-message: See ORIGIN_COMMIT from $GITHUB_REF
            target-branch: gh-pages
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
